// DOCKER COMPOSE METHOD

pipeline {
    agent { label 'linux' }
    stages {      
        stage('Cleanup') {
            steps {
                sh 'docker-compose stop production-order development-order'
                sh 'docker-compose rm production-order development-order'
                sh 'rm -r *'
            }
        }
        stage('Clone') {
            steps {
                sh 'git clone https://github.com/Emmvish/Online-Shopping.git .'
                sh "find . -mindepth 1  ! -regex '^./order\(/.*\)?' -delete"
            }
        }
        stage('Test & Deploy') {
            steps {
                sh 'cd order && docker-compose up --detach --build production-order development-order'
            }
        }
    }
} 


// PURE DOCKER CLIENT METHOD

// pipeline {
//     agent { label 'linux' }
//     stages {      
//         stage('Cleanup') {
//             steps {
//                 sh 'docker stop order order-test'
//                 sh 'docker rm order order-test'
//                 sh 'rm -r *'
//             }
//         }
//         stage('Clone') {
//             steps {
//                 sh 'git clone https://github.com/Emmvish/Online-Shopping.git .'
//                 sh "find . -mindepth 1  ! -regex '^./order\(/.*\)?' -delete"
//             }
//         }
//         stage('Test') {
//             steps {
//                 sh 'cd order && docker build -f Dockerfile.dev -t emmvish/order-test:latest .'
//                 sh 'docker run -d --name order-test emmvish/order-test:latest '
//             }
//         }
//         stage('Deploy') {
//             steps {
//                 sh 'cd order && docker build -t emmvish/order:latest .'
//                 sh 'docker run -d -p ${PORT}:4007 --name order emmvish/order:latest'
//             }
//         }
//     }
// } 


// JENKINS-DOCKER PLUGIN METHOD

// pipeline {
//     agent { label 'linux' }
//     stages {      
//         stage('Cleanup') {
//             steps {
//                 sh 'docker stop order order-test'
//                 sh 'docker rm order order-test'
//                 sh 'rm -r *'
//             }
//         }
//         stage('Clone') {
//             steps {
//                 sh 'git clone https://github.com/Emmvish/Online-Shopping.git .'
//                 sh "find . -mindepth 1  ! -regex '^./order\(/.*\)?' -delete"
//             }
//         }
//         stage('Test') {
//             agent {
//                 dockerfile { 
// 			           filename 'Dockerfile.dev'
//                     dir 'order'
//                     label 'linux'
//                     args '-d --name order-test'
// 		        }
//             }
//             steps {
//                 sh 'node -v'
//                 sh 'npm -v'
//             }
//         }
//         stage('Deploy') {
//             agent {
//                 dockerfile { 
// 			           filename 'Dockerfile'
//                     dir 'order'
//                     label 'linux'
//                     args '-d -p ${PORT}:4007 --name order'
// 		        }
//             }
//             steps {
//                 sh 'node -v'
//                 sh 'npm -v'
//             }
//         }
//     }
// } 