version: '3'
services: 
  production-research:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    env_file:
      - ./config/config.env
  development-research:
    build:
      context: .
      dockerfile: Dockerfile.dev