// DOCKER COMPOSE METHOD

pipeline {
    agent { label 'linux' }
    stages {      
        stage('Cleanup') {
            steps {
                sh 'docker-compose stop production-event-bus'
                sh 'docker-compose rm production-event-bus'
                sh 'rm -r *'
            }
        }
        stage('Clone') {
            steps {
                sh 'git clone https://github.com/Emmvish/Online-Shopping.git .'
                sh "find . -mindepth 1  ! -regex '^./event-bus\(/.*\)?' -delete"
            }
        }
        stage('Deploy') {
            steps {
                sh 'cd event-bus && docker-compose up --detach --build production-event-bus'
            }
        }
    }
} 