// DOCKER COMPOSE METHOD

pipeline {
    agent { label 'linux' }
    stages {      
        stage('Cleanup') {
            steps {
                sh 'docker-compose stop production-cart development-cart'
                sh 'docker-compose rm production-cart development-cart'
                sh 'rm -r *'
            }
        }
        stage('Clone') {
            steps {
                sh 'git clone https://github.com/Emmvish/Online-Shopping.git .'
                sh "find . -mindepth 1  ! -regex '^./cart\(/.*\)?' -delete"
            }
        }
        stage('Test & Deploy') {
            steps {
                sh 'cd cart && docker-compose up --detach --build production-cart development-cart'
            }
        }
    }
} 


// PURE DOCKER CLIENT METHOD

// pipeline {
//     agent { label 'linux' }
//     stages {      
//         stage('Cleanup') {
//             steps {
//                 sh 'docker stop cart cart-test'
//                 sh 'docker rm cart cart-test'
//                 sh 'rm -r *'
//             }
//         }
//         stage('Clone') {
//             steps {
//                 sh 'git clone https://github.com/Emmvish/Online-Shopping.git .'
//                 sh "find . -mindepth 1  ! -regex '^./cart\(/.*\)?' -delete"
//             }
//         }
//         stage('Test') {
//             steps {
//                 sh 'cd cart && docker build -f Dockerfile.dev -t emmvish/cart-test:latest .'
//                 sh 'docker run -d --name cart-test emmvish/cart-test:latest '
//             }
//         }
//         stage('Deploy') {
//             steps {
//                 sh 'cd cart && docker build -t emmvish/cart:latest .'
//                 sh 'docker run -d -p 4006:4006 --name cart emmvish/cart:latest'
//             }
//         }
//     }
// } 


// JENKINS-DOCKER PLUGIN METHOD

// pipeline {
//     agent { label 'linux' }
//     stages {      
//         stage('Cleanup') {
//             steps {
//                 sh 'docker stop frontend frontend-test'
//                 sh 'docker rm frontend frontend-test'
//                 sh 'rm -r *'
//             }
//         }
//         stage('Clone') {
//             steps {
//                 sh 'git clone https://github.com/Emmvish/Online-Shopping.git .'
//                 sh "find . -mindepth 1  ! -regex '^./cart\(/.*\)?' -delete"
//             }
//         }
//         stage('Test') {
//             agent {
//                 dockerfile { 
// 			           filename 'Dockerfile.dev'
//                     dir 'cart'
//                     label 'linux'
//                     args '-d --name cart-test'
// 		        }
//             }
//             steps {
//                 sh 'node -v'
//                 sh 'npm -v'
//             }
//         }
//         stage('Deploy') {
//             agent {
//                 dockerfile { 
// 			           filename 'Dockerfile'
//                     dir 'cart'
//                     label 'linux'
//                     args '-d -p 4006:4006 --name cart'
// 		        }
//             }
//             steps {
//                 sh 'node -v'
//                 sh 'npm -v'
//             }
//         }
//     }
// } 